#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert|change)(\(.+?\))?: .{1,}$"; then
    echo "Commit messages should start with feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert|change" >&2
    echo "Example -> docs: Update README" >&2
    echo "Automatically prepending 'change:' to commit msg " >&2
    COMMITMSG=$(cat "${1}")
    echo ${COMMITMSG} | sed -Ei 's/^/change\: /'
    echo "${COMMITMSG}" 
    git commit -S -msg "${COMMITMSG}"
    exit 0
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "Aborting commit: Commit message too long.  88 Characters is max length." >&2
    exit 1
fi