#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert|change)(\(.+?\))?: .{1,}$"; then
    echo "Commit messages should start with feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert|change -> then ': '" >&2
    echo "Example -> docs: Update README" >&2
    OLDMSG=$(cat "${1}")
    echo "Automatically prepending 'change:' to commit msg -> ${OLDMSG}" >&2
    NEWMSG=$(echo "${OLDMSG}" | sed -e 's/^/change\: /')
    echo "${NEWMSG}" > "${1}" 
    exit 0
fi